name: Deploy node serverless aws

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        # install serverless
      - name: Install serverless framework
        run: npm install -g serverless
        # setup aws credentials
      - name: Serverless AWS credentials
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # install node modules
      - name: Install npm dependencies
        run: npm install
        # create ENV
      - name: Create env file
        run: |
          cat > .env << EOF
          ${{ secrets.ENV }}
          EOF
        # deploy serverless
      - name: Deploy dev
        run: npm run deploy:dev
